# Generated by Django 3.2.7 on 2021-09-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/%y', verbose_name='')),
                ('chores', models.CharField(blank=True, max_length=1000, null=True, verbose_name='')),
                ('homework', models.CharField(blank=True, max_length=1000, null=True, verbose_name='')),
                ('recreational', models.CharField(blank=True, max_length=1000, null=True, verbose_name='')),
            ],
        ),
    ]
