# Generated by Django 3.2.7 on 2021-09-07 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0011_auto_20210905_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y', verbose_name=''),
        ),
    ]
