# Generated by Django 3.2.7 on 2021-09-11 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0012_alter_kid_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='chores',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='homework',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='todo',
            name='recreational',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name=''),
        ),
    ]
