# Generated by Django 3.2.7 on 2021-09-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parenting', '0013_auto_20210911_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kid',
            name='id',
        ),
        migrations.AddField(
            model_name='kid',
            name='kid_id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
